#Application
spring.application.name=library-management

# Active profile (override this per environment)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.swagger-ui.enabled=true

# Custom path for the Swagger UI (e.g. http://localhost:8080/library-docs)
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for the JSON API definition
springdoc.api-docs.path=/v1/api-docs

## Ensure it scans your specific component packages
#springdoc.packages-to-scan=com.yourdomain.library.book, com.yourdomain.library.borrower, com.yourdomain.library.record
#
## Enable sorting of endpoints alphabetically
springdoc.swagger-ui.operationsSorter=alpha
